treasure_cruise:
  build: src
  links:
    - postgres
  volumes:
    - ./src/:/treasure_cruise
  environment:
      MODE: prices
      NUMBER_OF_CARDS: 52431

postgres:
  image: postgres
  environment:
    POSTGRES_USER: tc123
    POSTGRES_PASSWORD: tc123
    POSTGRES_DB: MTG
  ports:
    - 5433:5432
  restart: always
  volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

