notebook:
  build: src/learning
  ports:
    - 8787:8888
  volumes:
    - ./src/learning:/notebooks
    - ./src/gathering/data:/notebooks/data

treasure_cruise:
  build: src/gathering
  links:
    - postgres
  volumes:
    - ./src/gathering:/treasure_cruise
  environment:
    GATHERER_CARD_ID_RANGE: 1-52431
    GATHERER_TCP_CONNECTION_LIMIT: 10
    SKIP_ERRORS: 0

postgres:
  image: postgres
  environment:
    POSTGRES_USER: tc123
    POSTGRES_PASSWORD: tc123
    POSTGRES_DB: MTG
  restart: always
  volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

